### PR TITLE
use busybox wget

### PR DESCRIPTION
**Pull request by elysias123**
Use busybox wget can reduce a lot of zip volume.

### CODE REVIEW

**Comment by vladrevers** [comment]
@heinu123 will there be support for Apatch and KSU after this?
PS I did about the same for myself, but I use Magisk and have not had a chance to check in others.

@daboynb Sorry for the offtopic, but the issues are closed.
Here in this feature ping endlessly every second until there are three successful attempts, this seems like overkill considering the user could just turn off the internet/wifi...
https://github.com/daboynb/PlayIntegrityNEXT/blob/73d6410a1e15d7fb28b05e1191893e69f971cacb/playcurl/service.sh#L27

**Comment by daboynb** [comment]
> ~~@heinu123 will there be support for Apatch and KSU after this?
> PS I did about the same for myself, but I use Magisk and have not had a chance to check in others.~~
> 
> @daboynb Sorry for the offtopic, but the issues are closed.
> Here in this feature ping endlessly every second until there are three successful attempts, this seems like overkill considering the user could just turn off the internet/wifi...
> https://github.com/daboynb/PlayIntegrityNEXT/blob/73d6410a1e15d7fb28b05e1191893e69f971cacb/playcurl/service.sh#L27

The internet check is done every 30 minutes, you can change the time editing the seconds.txt file.

**Comment by vladrevers** [comment]
> If the network is down after 3 pings the script goes to sleep.

this does not happen, in your code, with each unsuccessful attempt, the counter is reset to 0, and the exit conditions from the loop are the counter greater than 3

**Comment by daboynb** [comment]
You're right, thanks!

**Comment by heinu123** [comment]
> ~@heinu123 will there be support for Apatch and KSU after this? PS I did about the same for myself, but I use Magisk and have not had a chance to check in others.~
> 
> @daboynb Sorry for the offtopic, but the issues are closed. Here in this feature ping endlessly every second until there are three successful attempts, this seems like overkill considering the user could just turn off the internet/wifi...
> 
> https://github.com/daboynb/PlayIntegrityNEXT/blob/73d6410a1e15d7fb28b05e1191893e69f971cacb/playcurl/service.sh#L27

all busybox under /data/adb are automatically found.

**Comment by daboynb** [comment]
I revered some commits since wget wasn't working for some ppl, I need to look deeper... as for busybox, it seems ok for now to me

**Comment by heinu123** [comment]
> I revered some commits since wget wasn't working for some ppl, I need to look deeper... as for busybox, it seems ok for now to me

It seems that there is no busybox?

**Pull request merged**
