### PR TITLE
Extending some acronyms

### PR DESCRIPTION
**Pull request by bphd**

### CODE REVIEW

**Review by furdiburd — APPROVED** [review]
seems fine. :) other than the playintegrityfix.json

**Comment by bphd** [comment]
Why NEXT don't rebase on the 112 changes made on FIX upstream?

**Comment by furdiburd** [comment]
> Why NEXT don't rebase on the 112 changes made on FIX upstream?

Cuz its working fine right now?

**Comment by bphd** [comment]
> > Why NEXT don't rebase on the 112 changes made on FIX upstream?
> 
> Cuz its working fine right now?

Seems totally logical, if it works, don't touch it

PIF integrated kind of same work as MSK, like it deleted the problematic part and made an "API" for anybody to insert what he needs. On MSK it gave for example MSKHide or ZygiskNext or Shamiko. But PINEXT don't seems to use that new system, it use old version before it was implemented, version where PIF still gave directly the solution hardcoded

**Comment by daboynb** [comment]
> > > Why NEXT don't rebase on the 112 changes made on FIX upstream?
> > 
> > 
> > Cuz its working fine right now?
> 
> Seems totally logical, if it works, don't touch it
> 
> PIF integrated kind of same work as MSK, like it deleted the problematic part and made an "API" for anybody to insert what he needs. On MSK it gave for example MSKHide or ZygiskNext or Shamiko. But PINEXT don't seems to use that new system, it use old version before it was implemented, version where PIF still gave directly the solution hardcoded. All that while being kind of ZygiskNext but PiNext, maybe more comparable to MSKDelta/Alpha who splitted their way out of that API work. Maybe it would be logical too to try if a rebase makes it work, if yes push a new version with the changes, so it won't be a major fork like Delta/Alpha but rather a soft fork like Hide/Shamiko/Next. Or at least don't hesitate cherry pick some common sense commits

I made some tests, I've found an easy way to implement the custom fp download but the xiaomi.eu fp is not working on play integrity fix next 14.9, idk why.

**Comment by daboynb** [comment]
> _ No description provided. _

Thank you but the file is named pif.json, some people will get confused if I rename it to playIntegrityFix.json, they will search for a non-existent file.

**Comment by bphd** [comment]
> > > > Why NEXT don't rebase on the 112 changes made on FIX upstream?
> > > 
> > > 
> > > Cuz its working fine right now?
> > 
> > 
> > Seems totally logical, if it works, don't touch it
> > PIF integrated kind of same work as MSK, like it deleted the problematic part and made an "API" for anybody to insert what he needs. On MSK it gave for example MSKHide or ZygiskNext or Shamiko. But PINEXT don't seems to use that new system, it use old version before it was implemented, version where PIF still gave directly the solution hardcoded. All that while being kind of ZygiskNext but PiNext, maybe more comparable to MSKDelta/Alpha who splitted their way out of that API work. Maybe it would be logical too to try if a rebase makes it work, if yes push a new version with the changes, so it won't be a major fork like Delta/Alpha but rather a soft fork like Hide/Shamiko/Next. Or at least don't hesitate cherry pick some common sense commits
> 
> I made some tests, I've found an easy way to implement the custom fp download but the xiaomi.eu fp is not working on play integrity fix next 14.9, idk why.

Cherry pick commit till finding culprit

**Pull request closed without merging**
